djangofilm/urls.py
import myapp as myapp
from django.contrib import admin
from django.urls import path, include
from catalog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='home'),
    path('kino/',views.Kinolist.as_view(), name='allkino'),
    path('actor/',views.Actorlist.as_view(), name='allactor'),
    path('director/',views.Directorlist.as_view(), name='alldirector'),
    # path('kino/<int:id>/',views.info, name='info'),
    path('kino/<slug:pk>/<str:title>',views.KinoDetail.as_view(), name='info'),
    path('actor/<slug:pk>/<str:title>',views.ActorDetail.as_view(), name='infoactor'),
    path('director/<slug:pk>/<str:title>',views.DirectorDetail.as_view(), name='infodirector'),
    path('user/', include('django.contrib.auth.urls')),
    path('status/',views.status,name='status'),
    path('status/prosmotr/<int:id1>/<int:id2>/<int:id3>',views.prosmotr,name='prosmotr'),
    path('status/buy/<int:type>/',views.buy, name= 'buystatus'),
    path('kup_podpiska/', views.kup_podpiska, name='kup_podpiska'),
    path('otpiska/<int:type>/', views.otpiska, name='otpiska'),
    path('status/registr/',views.registr,name='registr'),
    path('search/', views.search_films, name='search_films'),






]
'''
login
reset_form
reset_done
reset_confirm
reset_complete
'''

catalog/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=20, verbose_name='Жанр')

    def __str__(self):
        return self.name

class Director(models.Model):
    fname = models.CharField(max_length=20, verbose_name='Имя')
    lname = models.CharField(max_length=20, verbose_name='Фамилия')

    def __str__(self):
        return f'{self.fname},{self.lname}'
    def get_absolute_url(self):
        return reverse('infodirector', args=[self.id, self.lname])

class Actor(models.Model):
    fname = models.CharField(max_length=20, verbose_name='Имя')
    lname = models.CharField(max_length=20, verbose_name='Фамилия')
    born = models.DateField(null=True, blank=False, verbose_name='Дата рождения')
    country = models.CharField(max_length=20, verbose_name='Страна')

    def __str__(self):
        return self.lname

    def get_absolute_url(self):
        return reverse('infoactor', args=[self.id, self.lname])



class Status(models.Model):
    VIBOR = (('бесплатно','бесплатно'),('базовая','базовая'),('супер','супер'))
    name = models.CharField(max_length=20, choices=VIBOR, verbose_name='Подписка')

    def __str__(self):
        return self.name

class Country(models.Model):
    name = models.CharField(max_length=20, verbose_name='Страна')

    def __str__(self):
        return self.name

class AgeRate(models.Model):
    choise = (('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'))
    rate = models.CharField(max_length=20, choices=choise, verbose_name='Рейтинг')

    def __str__(self):
        return self.rate

class Kino(models.Model):
    title = models.CharField(max_length=20, verbose_name='Название')
    genre = models.ForeignKey(Genre, on_delete=models.SET_DEFAULT, default=1)
    rating = models.FloatField(verbose_name='Оценка')
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    director = models.ForeignKey(Director, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=500, verbose_name='Описание')
    year = models.IntegerField(verbose_name='Год')
    ager = models.ForeignKey(AgeRate, on_delete=models.SET_NULL, null=True)
    actor = models.ManyToManyField(Actor, verbose_name='Актеры')
    status = models.ForeignKey(Status, on_delete=models.SET_DEFAULT, default=1)
    image = models.CharField(max_length=100, blank=True, null=True, verbose_name="Картинка")

    def __str__(self):
        return self.title

    def display_actors(self):
        res=''
        for a in self.actor.all():
            res+=a.lname+' '
        return res
    display_actors.short_description='Актеры'

    def get_absolute_url(self):
        return reverse('info', args=[self.id, self.title])
        # return f'kino'/{self.id}/{self.title}

from django.db import models
from django.contrib.auth.models import User

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

templates/buy.html
{% extends 'index.html' %}
{% block content %}
    <h2>Вы купили подписку{{ podpiska }}</h2>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head %}
    <title>кино</title>
    <link rel="stylesheet" href="{% static 'css.css' %}">
    {% endblock head %}
</head>
<body>
    {% block menu %}
    <div class="menu">
        <a href="{% url 'allkino' %}">Фильмы</a>
        <a href="{% url 'allactor' %}">Актеры</a>
        <a href="{% url 'alldirector' %}">Режисеры</a>
        <a href="{%  url 'status' %}">Подписка</a>
<a href="{% url 'search_films' %}">Поиск фильмов</a>



  <a href="{% url 'kup_podpiska' %}">Подписка купить</a>


        {% if not user.username %}
            <a href="{% url 'login' %}">Login</a>
        {% else %}
            <a href="{% url 'logout' %}">Logout</a>
        {% endif %}


    </div>
    {% endblock menu %}
    {% block content %}
    <h1>Привет {{ username }}</h1>
    <h2>Каталог фильмов</h2>
        <h2>На сайте {{ k1 }} фильмов</h2>
        <h2>На сайте {{ k2 }} актеров</h2>
        <h2>На сайте {{ k3 }} фильмов бесплатно</h2>

    {% endblock content %}

<a href="{% url 'admin:index' %}">Админка</a>

</body>
</html>

templates/podpiska.html
{% extends 'index.html' %}
{% load static %}
{% block head %}
    <title>кино</title>
    <link rel="stylesheet" href="{% static 'css.css' %}">
    <link rel="stylesheet" href="{% static 'podpiska.css' %}">
    {% endblock head %}
{% block content %}
    <h2>Подписки</h2>
    {% for one in podpiska %}
        <h3 class="main">{{ one.name }}</h3>
        <div class="cont">
        {% for kino in one.kino_set.all %}
        <div class="card">
        <img src="{% static kino.image%}" alt="">
        <h4>{{ kino.title }}</h4>
        <h4>{{ kino.genre }}</h4>
        {% if not user.username %}
        <a href="{% url 'prosmotr' kino.id one.id 0 %}">
            <button>Смотреть</button>
        </a>
        {% else %}
        <a href="{% url 'prosmotr' kino.id one.id user.id %}">
            <button>Смотреть</button>
        </a>
        {% endif %}
        </div>
    {% endfor %}
        </div>
    {% endfor %}
{% endblock content %}

templates/pokypka.html
{% extends 'index.html'%}
{% load static %}
 {%  block head %}
    <title>Форма подписки</title>
        <link rel="stylesheet" href="{% static 'css.css' %}">
{#        <link rel="stylesheet" href="{% static 'css/otsuper.css' %}">#}
    {% endblock %}
{% block content %}
    <div class="user">
        <h1>Привет {{ user.username.title }}</h1>
        <h4> Имя:	{{ user.first_name }}</h4>
        <h4>Фамилия:	{{ user.last_name }}</h4>
        <h4>Email:	{{ user.email }}</h4>
        <h4>Подписка:	<i>{{ user.groups.all.0 }}</i></h4>
    </div>
    <div class="kupitpodpis">
        <h3>Купить подписку:</h3>
       {% if user.groups.all.0.id == 1%}
           <h4><a href="{% url 'buystatus' type=2%}">Купить базовую</a></h4>
           <h4><a href="{% url 'buystatus' type=3%}">Купить супер</a></h4>
             {% elif  user.groups.all.0.id == 2 %}
           <h4><a href="{% url 'buystatus' type=3%}">Купить супер</a></h4>
{#        {% else %}#}
{#            <h4>Приятного просмотра</h4>#}
        {% endif %}
    </div>
    <div class="otkazpodris">
    <h3>Отказаться от подписки:</h3>
        {% if user.groups.all.0.id == 3 %}
            <h3><a href="{% url 'otpiska' type=2%}">От Super</a></h3>
             <h3><a href="{% url 'otpiska' type=1%}">От Based</a></h3>
        {% elif user.groups.all.0.id == 2 %}
    <h3><a href="{% url 'otpiska' type=1%}">От Based</a></h3>
        {% endif %}
    </div>

{% endblock content %}

templates/prosmotr.html
{% extends 'index.html' %}
{% load static %}
 {% block head %}
    <title>Просмотры</title>
    <link rel="stylesheet" href="{% static 'css.css' %}">
    <link rel="stylesheet" href="{% static 'prosmotr.css' %}">
    {% endblock head %}
{% block content %}
    <h3>Фильм {{ kino }}</h3>
    <div class="screen">
        {% if prava %}
            <h4>Приятного просмотра</h4>
        {% else %}
            <h4>Купите подписку</h4>
        {% endif %}


    </div>
    <h3>Ваша подписка {{ status }}</h3>
    <h3>Для фильма {{ statuskino }}</h3>

        {% if not prava %}
            {% if user.username %}
            <h4>
            <a href="{% url 'buystatus' type=2 %}">Купить базовую</a>
            </h4>

            <h4>
            <a href="{% url 'buystatus' type=3 %}">Купить супер</a>
            </h4>
                {% else %}
                  <h4>
            <a href="{% url 'login' %}">Купить базовую</a>
            </h4>

            <h4>
                <a href="{% url 'login' %}">Купить супер</a></h4>
                {% endif %}
        {% endif %}
{% endblock %}

templates/search.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
фв
    <form method="get" action="{% url 'search_films' %}">
    {{ form.as_p }}
    <button type="submit">Искать</button>
</form>
{% endblock content %}

templates/search_results.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
    <h2>Результаты поиска для "{{ query }}"</h2>
 <h1>Результаты поиск</h1>
   {% for film in films %}
    <div class="film-card">
        <h3>{{ film.title }}</h3>
        <p>{{ film.summary }}</p>
<a href="{% url 'info' pk=film.pk title=film.title %}">Подробнее</a>
    </div>
{% empty %}
    <p>Ничего не найдено.</p>
{% endfor %}
{% endblock content %}